### ISSUE TITLE
redesign mails sent; inform users about role/provider changes

### ISSUE THREAD

**Issue by ScrambledRK** [newhere-team/nh-website#41]
* the actual mail address that should be used is "info at" not "help at"
* buttons should be blue not sunny orange
* the text should probably a little bit more descriptive about what is going

currently there are the following mails sent:
* registration: verify mail account and follow generated link
* reset password: follow generated link to set a new password

it may be a good idea to also send a mail in case:
* user has been disabled/enabled (likely unnecessary for now)
* user has been granted new permissions (assigned to a provider, given a new role)

**Comment by ScrambledRK** [comment]
how it looks now ...

![mail_nh](https://user-images.githubusercontent.com/1149332/36153341-3c7d080c-10ce-11e8-923b-7a62116e1004.jpg)

**Comment by ScrambledRK** [comment]
fixed the typos as far as my english checks out

**Comment by ScrambledRK** [comment]
should we send mails on user-profile-changes?
e.g. they are assigned a new role (translator) or join/create a provider?

**Comment by kmay90** [comment]
Style-wise it looks great. I would suggest the following change to the text: 'Please follow the link below to confirm your registration. Your account will then be activated and you will be able to log in begin adding your provider and offers to the platform, or registering as a translator.'

Re: mails on user-profile changes, at some point it might be good to send an email when we verify something e.g. allow offers to show on map, make someone a translator.

Question: do we have to verify before a provider shows on the map, or does this happen automatically? Ideally this would also have to be verified so that people cannot create a provider that goes against the principles of NewHere and publish it online without our knowledge.

**Comment by ScrambledRK** [comment]
alright, I'll change the text and do my best to translate it to german (after all this translation I doubt my german). I'll keep the "user-profile changes" mail in mind but will not implement it as of yet.

regarding your question: newly created providers are by default disabled and hidden and must be unlocked by an administrator. It is a bug if reality contradicts this :P - I'm going to check this again though.

**Comment by ScrambledRK** [comment]
k, closed then - and new issues shall be created in case anything comes up
